{
    "setup": {
        "segmentation": "GeneralSegmentation",
        "model_to_use": "UNet"
    },

    "service": {
        "runner_name": "bento_runner",
        "bento_model_path": "semantic-Unet",
        "service_name": "data-centric-platform",
        "port": 7010
    },

    "model": { 
        "classifier":{
            "in_channels": 1,
            "num_classes": 2,
            "features":[64,128,256,512]
        }
    },

    "data": {
        "data_root": "data",
        "accepted_types": [".jpg", ".jpeg", ".png", ".tiff", ".tif"],
        "seg_name_string": "_seg",
        "gray": True,
        "rescale": True
    },

    "train":{
        "classifier":{
            "n_epochs": 2,
            "lr": 0.001,
            "batch_size": 1,
            "optimizer": "Adam"
        }
    },

    "eval":{
        "classifier": {
            
        },
        "compute_instance": True,
        "mask_channel_axis": 0
    }
}