{
    "setup": {
        "segmentation": "GeneralSegmentation",
        "model_to_use": "MultiCellpose", 
        "accepted_types": [".jpg", ".jpeg", ".png", ".tiff", ".tif"],
        "seg_name_string": "_seg"
    },

    "service": {
        "runner_name": "bento_runner",
        "bento_model_path": "test1w",
        "service_name": "data-centric-platform",
        "port": 7010
    },

    "model": { 
        "segmentor_name": "Cellpose",
        "segmentor": {
            "model_type": "cyto"
            
        },
        "classifier_name": "PatchClassifier",
        "classifier":{
            "in_channels": 1,
            "num_classes": 2,
            "features":[64,128,256,512],
            "black_bg": False,
            "include_mask": True
        }
    },

    "data": {
        "data_root": "data",
        "patch_size": 64,
        "noise_intensity": 5,
        "gray": True,
        "rescale": True
    },

    "train":{
        "segmentor":{
            "n_epochs": 5,
            "channels": [0,0],
            "min_train_masks": 1
        },
        "classifier":{
            "n_epochs": 100,
            "lr": 0.001,
            "batch_size": 1,
            "optimizer": "Adam"
        }
    },

    "eval":{
        "segmentor": {
            "z_axis": null,
            "channel_axis": null,
            "rescale": 1,
            "batch_size": 1
        },
        "classifier": {
        },
        "mask_channel_axis": 0
    }
}